name: build, test and deploy to cloud run
on:
  issues:

jobs:
  build-test-create-dockerimage:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: test secrets
        run: echo secret "${{secrets.WIF_PROVIDER }}　% ${{secrets.WIF_SERVICE_ACCOUNT }}" | sed 's/./& /g'
      - uses: actions/checkout@v4
      - name: 'Google auth'
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: '${{secrets.WIF_PROVIDER}}' # e.g. - projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider
          service_account: '${{secrets.WIF_SERVICE_ACCOUNT}}' # e.g. - my-service-account@my-project.iam.gserviceaccount.com
          
#      - name: 'Set up Cloud SDK'
#        uses: 'google-github-actions/setup-gcloud@v1'
#        with:
#          project_id: '${{secrets.PROJECT_ID}}'

#      - name: 'Docker auth'
#        run: |-
#          gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev
      
#      - name: 'Build and push container'
#        run: |-
#          docker build -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.APP }}/${{ env.APP }}:${{ github.sha }}" ./app
#          docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.APP }}/${{ env.APP }}:${{ github.sha }}"
