name: build, test and deploy to cloud run
on:
  issues:

jobs:
  build-test-create-dockerimage:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: test secrets
        run: echo secret "${{secrets.WIF_PROVIDER }}　% ${{secrets.WIF_SERVICE_ACCOUNT }}　% ${{secrets.PROJECT_ID }}" | sed 's/./& /g'
      - uses: actions/checkout@v4
      - name: 'Google auth'
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: '${{secrets.WIF_PROVIDER}}'
          service_account: '${{secrets.WIF_SERVICE_ACCOUNT}}'
          
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 379.0.0'
          
      - name: 'Docker auth'
        run: |-
          gcloud auth configure-docker asia-northeast1-docker.pkg.dev,asia-east1-docker.pkg.dev
      
      - name: 'Build and push container'
        run: |-
          docker build -t "asia-northeast1-docker.pkg.dev/phrasal-vent-332015/spring-boot-restful-api-test:${{github.sha}}" .
          docker push "asia-northeast1-docker.pkg.dev/phrasal-vent-332015/spring-boot-restful-api-test:${{ github.sha }}"
