name: build deploy to cloud run
on:
  push:

jobs:
  build-test-create-dockerimage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'          # temurinでJDK8は利用可(oracle等はサポート対象外)
          java-version: '8'
      - name: build and test
        run: mvn test
  depoy-to-cloudrun:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'          # temurinでJDK8は利用可(oracle等はサポート対象外)
          java-version: '8'
      - name: build and test
        run: mvn test
