name: build, test and deploy to cloud run
on:
  issues:

env:
  ARTIFACT_REGISTRY: github-actions
  REGION: asia-northeast1
  APP_NAME: spring-boot-restful-api-test

jobs:
  build-test-deploy-to-cloudrun:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: 'Google auth'
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: '${{secrets.WIF_PROVIDER}}'
          service_account: '${{secrets.WIF_SERVICE_ACCOUNT}}'
          
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 379.0.0'
          
      - name: 'Docker auth'
        run: |-
          gcloud auth configure-docker ${{env.REGION}}-docker.pkg.dev
      
      - name: 'Build and push container'
        run: |-
          docker build -t "${{env.REGION}}-docker.pkg.dev/${{secrets.PROJECT_ID}}/${{ARTIFACT_REGISTRY}}/${{APP_NAME}}:${{github.sha}}" .
          docker push "${{env.REGION}}-docker.pkg.dev/${{secrets.PROJECT_ID}}/${{ARTIFACT_REGISTRY}}/${{APP_NAME}}:${{github.sha}}"

      - name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v0'
        with:
          service: ${{APP_NAME}}
          region: ${{env.REGION}}
          image: ${{env.REGION}}-docker.pkg.dev/${{secrets.PROJECT_ID}}/${{ARTIFACT_REGISTRY}}/${{APP_NAME}}:${{github.sha}}
