name: build, test and deploy to cloud run
on:
  push:
  
jobs:
  build-test-deploy-to-cloudrun:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      ARTIFACT_REGISTRY: github-actions
      REGION: asia-northeast1
      APP_NAME: spring-boot-restful-api-test
      
    steps:
      - uses: actions/checkout@v4
      - name: 'Google auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: '${{secrets.WIF_PROVIDER}}'
          service_account: '${{secrets.WIF_SERVICE_ACCOUNT}}'
          
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 379.0.0'
          
      - name: 'Docker auth'
        run: |-
          gcloud auth configure-docker ${{env.REGION}}-docker.pkg.dev
      
      - name: 'Build and push container'
        run: |-
          docker build -t "${{env.REGION}}-docker.pkg.dev/${{secrets.PROJECT_ID}}/${{env.ARTIFACT_REGISTRY}}/${{env.APP_NAME}}:${{github.sha}}" .
          docker push "${{env.REGION}}-adocker.pkg.dev/${{secrets.PROJECT_ID}}/${{env.ARTIFACT_REGISTRY}}/${{env.APP_NAME}}:${{github.sha}}"

      - name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v0'
        with:
          service: ${{env.APP_NAME}}
          region: ${{env.REGION}}
          image: ${{env.REGION}}-docker.pkg.dev/${{secrets.PROJECT_ID}}/${{env.ARTIFACT_REGISTRY}}/${{env.APP_NAME}}:${{github.sha}}
    
  slack-notification:
    name: send-notification
    if: always()
    needs: build-test-deploy-to-cloudrun
    runs-on: ubuntu-latest
    steps:
      - name: Send GitHub Action trigger data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "Build, Test and Deploy successful."
            }
        env:
          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}  
